name: Build and Release Nightly

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GTK3 and OpenSSL dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libssl-dev

      - name: Build project
        run: make

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: secure-note
          path: bin/secure-note

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Download executable
        uses: actions/download-artifact@v3
        with:
          name: secure-note

      - name: Create a Nightly Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-${{ github.run_id }}
          release_name: "Nightly Build - ${{ github.run_id }}"
          body: "This is an automated nightly release for the latest push to the dev branch."
          draft: false
          prerelease: true

      - name: Upload Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: bin/secure-note
          asset_name: secure-note
          asset_content_type: application/octet-stream
